services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "./srv/database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - path: .env
        required: true

  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8000:80
    restart: always
    environment:
      WORDPRES_DB_HOST: ${WORDPRES_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DEBUG: 1
    env_file:
      - path: .env
        required: true
    volumes:
      - ./srv/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./srv/wordpress/:/var/www/html
      - ./themes/krishna-academy/:/var/www/html/wp-content/themes/krishnaacademy

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: mysql
    env_file:
      - path: .env
        required: true
